<a href="https://colab.research.google.com/github/Abidah15/My_Notes-GColab/blob/main/Learn_4_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* **Pandas**: Python Data Analysis
* **Numpy**: Numerical Python
* **SciPy**: Scientific Python
* **Matplotlib**: Plotting library for Python (visualization)
* **Plotly**: 3D visualization

In [ ]:
import pandas as pd

'''creating a data set for sample of dataset by using dictionary'''
'''Creating a data frame from the dictionary'''
'''keys are the columns and values are the data'''

mydata = {

        'Name': ['Mohammed', 'Norul', 'Aziz', 'Fatimah'],
        'Age': [23,32,30,27],
        'City': ['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
        'Salary': [5000, 7000, 12000, 9000]
}

mydata

{'Name': ['Mohammed', 'Norul', 'Aziz', 'Fatimah'],
 'Age': [23, 32, 30, 27],
 'City': ['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
 'Salary': [5000, 7000, 12000, 9000]}

In [ ]:
#convert dictionary to data frame

df = pd.DataFrame(mydata)

df.head()

Name  Age          City  Salary
0  Mohammed   23  Kuala Lumpur    5000
1     Norul   32       Kuantan    7000
2      Aziz   30     Shah Alam   12000
3   Fatimah   27      Selangor    9000

In [ ]:
data1 = {
    'A':['A1', 'A2', 'A3', 'A4'],
    'B':['B1', 'B2', 'B3', 'B4'],
    'C':['C1', 'C2', 'C3', 'C4'],
    'D':['D1', 'D2', 'D3', 'D4']
}

data2 = {
    'A':['A5', 'A6', 'A7', 'A8'],
    'B':['B5', 'B6', 'B7', 'B8'],
    'C':['C5', 'C6', 'C7', 'C8'],
    'D':['D5', 'D6', 'D7', 'D8']
}

df_data1 = pd.DataFrame(data1)
df_data2 = pd.DataFrame(data2)

In [ ]:
df_data1.head()

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [ ]:
df_data2.head()

A   B   C   D
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [ ]:
df_data1_data2 = [df_data1, df_data2]

df_1_2 = pd.concat(df_data1_data2)

df_1_2.head(8)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [ ]:
#index.resetting

df_1_2 = df_1_2.reset_index(drop=True)

In [ ]:
df_1_2.head(8)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [ ]:
#we want to concatenate as columns

data3 = {
    'E':['E1','E2','E3','E4','E5','E6','E7','E8'],
    'F':['F1','F2','F3','F4','F5','F6','F7','F8'],
}

df_data3 = pd.DataFrame(data3)

pd.DataFrame(data3)

E   F
0  E1  F1
1  E2  F2
2  E3  F3
3  E4  F4
4  E5  F5
5  E6  F6
6  E7  F7
7  E8  F8

In [ ]:
df_all = [df_1_2, df_data3]
df_all = pd.concat(df_all, axis=1)

df_all.head(8)


A   B   C   D   E   F
0  A1  B1  C1  D1  E1  F1
1  A2  B2  C2  D2  E2  F2
2  A3  B3  C3  D3  E3  F3
3  A4  B4  C4  D4  E4  F4
4  A5  B5  C5  D5  E5  F5
5  A6  B6  C6  D6  E6  F6
6  A7  B7  C7  D7  E7  F7
7  A8  B8  C8  D8  E8  F8

In [ ]:
df_all.shape

(8, 6)

# **EXERCISE**

In [ ]:
import pandas as pd

In [ ]:
#create your own datasets, concatenate in terms of rows once, and in terms of columns once again.

In [ ]:
dataMY = {
    'Name': ['Abid','Afiq','Adib','Faiz','Amir'],
    'Age': [23, 24, 25, 26, 27],
    'Height': [165, 132, 174, 158, 109]
}

dataMY2 = {
    'Name': ['Thoha','Shakir','Shukor','Fateh','Farouq'],
    'Age': [34, 45, 21, 16, 13],
    'Height': [112, 134, 156, 163, 100]
}

df_dataMY = pd.DataFrame(dataMY)
df_dataMY2 = pd.DataFrame(dataMY2)


In [ ]:
df_dataMY.head()

Name  Age  Height
0  Abid   23     165
1  Afiq   24     132
2  Adib   25     174
3  Faiz   26     158
4  Amir   27     109

In [ ]:
df_dataMY2.head()

Name  Age  Height
0   Thoha   34     112
1  Shakir   45     134
2  Shukor   21     156
3   Fateh   16     163
4  Farouq   13     100

In [ ]:
df_dataMY_dataMY2 = [df_dataMY, df_dataMY2]
df_dataMY_dataMY2 = pd.concat(df_dataMY_dataMY2)
df_dataMY_dataMY2.head(10)

Name  Age  Height
0    Abid   23     165
1    Afiq   24     132
2    Adib   25     174
3    Faiz   26     158
4    Amir   27     109
0   Thoha   34     112
1  Shakir   45     134
2  Shukor   21     156
3   Fateh   16     163
4  Farouq   13     100

In [ ]:
df_dataMY_dataMY2 = df_dataMY_dataMY2.reset_index(drop=True)
df_dataMY_dataMY2

Name  Age  Height
0    Abid   23     165
1    Afiq   24     132
2    Adib   25     174
3    Faiz   26     158
4    Amir   27     109
5   Thoha   34     112
6  Shakir   45     134
7  Shukor   21     156
8   Fateh   16     163
9  Farouq   13     100

In [ ]:
dataMY3 = {
    'Address': ['Temerloh', 'Lumut', 'Pekan', 'Klang', 'Meru', 'Pekan', 'Inderapura', 'Temai', 'Serandu', 'Banting' ],
    'Salary': [3900,200,1250,2209,4030,710,2490,50,275,4990]
}

df_dataMY3 = pd.DataFrame(dataMY3)
df_dataMY3

Address  Salary
0    Temerloh    3900
1       Lumut     200
2       Pekan    1250
3       Klang    2209
4        Meru    4030
5       Pekan     710
6  Inderapura    2490
7       Temai      50
8     Serandu     275
9     Banting    4990

In [ ]:
df_all = (df_dataMY_dataMY2,df_dataMY3)
df_all = pd.concat(df_all,axis=1)
df_all

Name  Age  Height     Address  Salary
0    Abid   23     165    Temerloh    3900
1    Afiq   24     132       Lumut     200
2    Adib   25     174       Pekan    1250
3    Faiz   26     158       Klang    2209
4    Amir   27     109        Meru    4030
5   Thoha   34     112       Pekan     710
6  Shakir   45     134  Inderapura    2490
7  Shukor   21     156       Temai      50
8   Fateh   16     163     Serandu     275
9  Farouq   13     100     Banting    4990

In [ ]:
df_all.sample()

Name  Age  Height Address  Salary
4  Amir   27     109    Meru    4030

In [ ]:
df_all.sample(5)

Name  Age  Height     Address  Salary
9  Farouq   13     100     Banting    4990
7  Shukor   21     156       Temai      50
1    Afiq   24     132       Lumut     200
6  Shakir   45     134  Inderapura    2490
4    Amir   27     109        Meru    4030

In [ ]:
df_all.shape

(10, 5)

In [ ]:
df_all.columns

Index(['Name', 'Age', 'Height', 'Address', 'Salary'], dtype='object')

In [ ]:
df_all.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df_all2 = df_all.copy()
df_all2

Name  Age  Height     Address  Salary
0    Abid   23     165    Temerloh    3900
1    Afiq   24     132       Lumut     200
2    Adib   25     174       Pekan    1250
3    Faiz   26     158       Klang    2209
4    Amir   27     109        Meru    4030
5   Thoha   34     112       Pekan     710
6  Shakir   45     134  Inderapura    2490
7  Shukor   21     156       Temai      50
8   Fateh   16     163     Serandu     275
9  Farouq   13     100     Banting    4990

In [ ]:
df_all['Age'].mean()

25.4

In [ ]:
df_all['Height'].std()

26.529019749868045

In [ ]:
df_all['Salary'].max()

4990

In [ ]:
df_all['Salary'].min()

50

In [ ]:
df_all.iloc[[4],[0]]

Name
4  Amir

In [ ]:
df_all.iloc[5:8,0:4:3]

Name     Address
5   Thoha       Pekan
6  Shakir  Inderapura
7  Shukor       Temai

In [ ]:
df_all.loc[[6],['Salary']]

Salary
6    2490

In [ ]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     10 non-null     object
 1   Age      10 non-null     int64 
 2   Height   10 non-null     int64 
 3   Address  10 non-null     object
 4   Salary   10 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes


In [ ]:
import numpy as np

In [ ]:
array_df_all = np.array(df_all)
array_df_all

array([['Abid', 23, 165, 'Temerloh', 3900],
       ['Afiq', 24, 132, 'Lumut', 200],
       ['Adib', 25, 174, 'Pekan', 1250],
       ['Faiz', 26, 158, 'Klang', 2209],
       ['Amir', 27, 109, 'Meru', 4030],
       ['Thoha', 34, 112, 'Pekan', 710],
       ['Shakir', 45, 134, 'Inderapura', 2490],
       ['Shukor', 21, 156, 'Temai', 50],
       ['Fateh', 16, 163, 'Serandu', 275],
       ['Farouq', 13, 100, 'Banting', 4990]], dtype=object)

In [ ]:
array_df_all.ndim

2

**NOTES** vv

In [ ]:
import pandas as pd

df = pd.read_csv('NFLX.csv')
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
df.sample() #just one

Date        Open        High         Low       Close   Adj Close  \
831  2019-04-08  365.109985  365.940002  359.929993  361.410004  361.410004   

      Volume  
831  4653800

In [ ]:
df.sample(10)

Date        Open        High         Low       Close   Adj Close  \
575  2018-04-02  291.940002  292.869995  275.049988  280.290009  280.290009   
447  2017-09-26  180.699997  180.949997  176.550003  179.380005  179.380005   
662  2018-08-03  347.750000  347.859985  338.480011  343.089996  343.089996   
648  2018-07-16  398.980011  403.359985  391.750000  400.480011  400.480011   
267  2017-01-09  131.479996  131.990005  129.889999  130.949997  130.949997   
813  2019-03-13  355.809998  362.480011  352.769989  361.209991  361.209991   
444  2017-09-21  185.820007  189.949997  184.509995  188.779999  188.779999   
806  2019-03-04  359.720001  362.250000  348.040009  351.040009  351.040009   
936  2019-09-06  293.350006  293.350006  287.029999  290.170013  290.170013   
731  2018-11-09  311.070007  312.980011  298.010010  303.470001  303.470001   

       Volume  
575  13405800  
447   5602500  
662   8848400  
648  22960000  
267   5771800  
813   6444100  
444   7148100  
806   7487000  
936   5166600  
731  13480800

In [ ]:
df.shape

(1007, 7)

In [ ]:
df.index

RangeIndex(start=0, stop=1007, step=1)

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [ ]:
df2 = df.copy()
df2.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
df['High'].mean()

229.97297904468715

In [ ]:
df['Low'].std()

101.45861102484218

In [ ]:
df['Close'].max()

418.970001

In [ ]:
df['Close'].min()

82.790001

In [ ]:
#call cells

#df.iloc[[row index],[column index]]
df.iloc[[2],[3]]

Low
2  117.919998

In [ ]:
df.iloc[0:5,2:4] #pakai index

High         Low
0  123.000000  118.089996
1  126.349998  122.419998
2  122.190002  117.919998
3  119.589996  115.660004
4  117.430000  114.860001

In [ ]:
#df.loc[[row index],[column name]]

df.loc[[2],['High']]

High
2  122.190002

In [ ]:
df3 = df.iloc[:, 0:3] #want from the beginning until end of rows
df3

Date        Open        High
0     2015-12-16  119.800003  123.000000
1     2015-12-17  123.970001  126.349998
2     2015-12-18  120.849998  122.190002
3     2015-12-21  119.510002  119.589996
4     2015-12-22  117.300003  117.430000
...          ...         ...         ...
1002  2019-12-10  296.119995  298.940002
1003  2019-12-11  294.489990  299.429993
1004  2019-12-12  295.670013  299.170013
1005  2019-12-13  298.500000  301.799988
1006  2019-12-16  300.850006  305.709991

[1007 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1007 non-null   object 
 1   Open       1007 non-null   float64
 2   Test       1007 non-null   float64
 3   Test       1007 non-null   float64
 4   Close      1007 non-null   float64
 5   Adj Close  1007 non-null   float64
 6   Volume     1007 non-null   int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 55.2+ KB


In [ ]:
df.dtypes #to know all the data type

Date          object
Open         float64
Test         float64
Test         float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [ ]:
df.rename(columns={'High':'Test'},inplace=True)
df.head()

Date        Open        Test         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
df.rename(columns={'Low':'Test'})
df.head()

Date        Open        Test         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
df_test = df.rename(columns={'Low':'Test'},inplace=False)
df_test.head()


Date        Open        Test        Test       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
df.head()

Date        Open        Test         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

# **NUMPY**

In [ ]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8,9])
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrayS = np.array([[1,2],[3,4]])
arrayS

array([[1, 2],
       [3, 4]])

In [ ]:
arrayS.shape

(2, 2)

In [ ]:
arrayS.ndim

2

In [ ]:
type(array1) #n-dimension array

numpy.ndarray

**What is the difference berween List and Array?**

In Python, both lists and arrays are used to store collections of elements, but they have some differences in terms of functionality and implementation. Here's a breakdown of the key differences between lists and arrays in Python:

**Data Type:**
Lists: Lists in Python are a built-in data type and are part of the standard library. They can hold elements of different data types and are very flexible.
Arrays: Arrays in Python are not a built-in data type but are provided by external libraries like NumPy. Arrays are more rigid in terms of data types and often store homogeneous elements (elements of the same data type) for optimized computation.

**Functionality:**
Lists: Lists provide various methods and operations for adding, removing, and manipulating elements.
Arrays: Arrays, particularly those from libraries like NumPy, provide extensive mathematical operations and optimizations for numerical computations.

*Memory Efficiency:*
Lists: Lists in Python are less memory efficient compared to arrays because they store additional metadata for each element, such as the type of the element and its reference count.

*In summary, the choice between using lists or arrays depends on your specific needs. If you're dealing with general data storage and manipulation, lists are more suitable. If you're working with numerical data and require optimized computations, arrays from libraries like NumPy offer better performance and functionality.*

In [ ]:
#creating 2D array

array2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#creating 3D array

array3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                  [[10,11,12], [13,14,15], [16,17,18]],
                  [[19,20,21], [22,23,24], [25,26,27]]]
                  )
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
array1.shape

(9,)

In [ ]:
array2.shape

(3, 3)

In [ ]:
array2.shape

(3, 3)

In [ ]:
array1.ndim

1

In [ ]:
array2.ndim

2

In [ ]:
array3.ndim

3

In [ ]:
#using linspace

np.linspace(200,900,num=3)

array([200., 550., 900.])

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data
#only having float & integer

col1 = np.random.normal(250, 10, 500)
col2 = np.random.normal(100, 20, 500)
col3 = np.random.normal(750, 5, 500)

#create categorical data

categorical_data = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

col4 = np.random.choice(categorical_data, 500)
col5 = np.random.choice(categorical_data, 500)

#create date data

start_date = datetime(2022, 1, 1)
end_date = datetime(2024, 1, 1)

delta = end_date - start_date

date_list = [start_date + timedelta(days=x) for x in range(delta.days)]

col6 = np.random.choice(date_list, 500)

#combine all the columns/features

data = np.column_stack((col1, col2, col3, col4, col5, col6))

df = pd.DataFrame(data, columns = ['Num1', 'Num2', 'Num3', 'Cat1', 'Cat2', 'Date'])
#this right here to change the name of the column, use rename function for columns

df.head()

Num1        Num2        Num3 Cat1 Cat2       Date
0  250.439106   71.861518  747.131259    G    E 2023-05-11
1   234.18388   90.682639  750.050226    B    H 2022-09-15
2  254.376163   88.869899  752.169116    I    F 2022-07-27
3  240.928575  118.758968  745.484062    G    D 2022-03-02
4  253.791492   80.729417  750.677193    D    J 2022-10-03

In [ ]:
df.shape

(500, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Num1    500 non-null    object        
 1   Num2    500 non-null    object        
 2   Num3    500 non-null    object        
 3   Cat1    500 non-null    object        
 4   Cat2    500 non-null    object        
 5   Date    500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 23.6+ KB


In [ ]:
df.describe()

Date
count                            500
mean   2022-12-26 08:41:16.800000256
min              2022-01-01 00:00:00
25%              2022-06-24 18:00:00
50%              2022-12-22 00:00:00
75%              2023-07-05 00:00:00
max              2023-12-27 00:00:00

In [ ]:
df.describe(include='all')

Num1        Num2        Num3 Cat1 Cat2  \
count   500.000000  500.000000  500.000000  500  500   
unique  500.000000  500.000000  500.000000   10   10   
top     250.439106   71.861518  747.131259    A    B   
freq      1.000000    1.000000    1.000000   70   61   
mean           NaN         NaN         NaN  NaN  NaN   
min            NaN         NaN         NaN  NaN  NaN   
25%            NaN         NaN         NaN  NaN  NaN   
50%            NaN         NaN         NaN  NaN  NaN   
75%            NaN         NaN         NaN  NaN  NaN   
max            NaN         NaN         NaN  NaN  NaN   

                                 Date  
count                             500  
unique                            NaN  
top                               NaN  
freq                              NaN  
mean    2022-12-26 08:41:16.800000256  
min               2022-01-01 00:00:00  
25%               2022-06-24 18:00:00  
50%               2022-12-22 00:00:00  
75%               2023-07-05 00:00:00  
max               2023-12-27 00:00:00

In [ ]:
df['Num1'] = df['Num1'].astype('float')

df[['Num2', 'Num3']] = df[['Num2', 'Num3']].astype('float')

df.dtypes

Num1           float64
Num2           float64
Num3           float64
Cat1            object
Cat2            object
Date    datetime64[ns]
dtype: object

In [ ]:
df.describe()

Num1        Num2        Num3                           Date
count  500.000000  500.000000  500.000000                            500
mean   250.175920  101.065953  749.858759  2022-12-26 08:41:16.800000256
min    217.924237   42.216185  736.632414            2022-01-01 00:00:00
25%    242.853222   87.012837  746.340286            2022-06-24 18:00:00
50%    250.228931  100.824159  749.673290            2022-12-22 00:00:00
75%    257.969644  114.173612  753.305503            2023-07-05 00:00:00
max    279.559615  171.436685  765.014953            2023-12-27 00:00:00
std     10.562193   20.456636    5.009378                            NaN

In [ ]:
df.describe(include='all')

Num1        Num2        Num3 Cat1 Cat2  \
count   500.000000  500.000000  500.000000  500  500   
unique         NaN         NaN         NaN   10   10   
top            NaN         NaN         NaN    A    B   
freq           NaN         NaN         NaN   70   61   
mean    250.175920  101.065953  749.858759  NaN  NaN   
min     217.924237   42.216185  736.632414  NaN  NaN   
25%     242.853222   87.012837  746.340286  NaN  NaN   
50%     250.228931  100.824159  749.673290  NaN  NaN   
75%     257.969644  114.173612  753.305503  NaN  NaN   
max     279.559615  171.436685  765.014953  NaN  NaN   
std      10.562193   20.456636    5.009378  NaN  NaN   

                                 Date  
count                             500  
unique                            NaN  
top                               NaN  
freq                              NaN  
mean    2022-12-26 08:41:16.800000256  
min               2022-01-01 00:00:00  
25%               2022-06-24 18:00:00  
50%               2022-12-22 00:00:00  
75%               2023-07-05 00:00:00  
max               2023-12-27 00:00:00  
std                               NaN